# Solutions of Practise Workbook A 

## Outline of Topics

1. Setting up your own github page and forking a repo
2. Files for Input and Output
3. Write a function to reverse the order of a file.


#### **Task 1**:

Setting up your own github account.  
Watch the following youtube video from former Purdue student Yang Wang on setting up your own github account:  
<a href="https://www.youtube.com/watch?v=ZhHDfZ-l7ZU" target="_blank">REEU Tutorial 1: Sign Up for Github</a>  
Then create your own github account.

#### **Task 2**:

Forking a repo.  
Watch the following youtube video from former Purdue student Yang Wang on setting up your own github account:  
<a href="https://www.youtube.com/watch?v=ZB9VgHFqqXU" target="_blank">REEU Tutorial 2: Fork a Github Repository</a>  
Then fork the repo ...

#### **Task 3:**  
Download and install VSCode.  
Install the environment in VSCode, install python.  
<a href="ASABEPaperPythonTutorial-main\Install VSCode for your local machine.docx" target="_blank">VSCode installation instructions</a>  


#### **Task 4**: Field Capacity Problem

The formula for field capacity is `C = S*W*E/8.25` where the units of C are acres/hour and
* S = tractor speed in mph
* W = width of implement in feet
* E = efficiency of swath (a fraction between 0 and 1)

Let `E = 0.85`.

Let `S` range from 3 to 7 in 0.5 mph increments

Let `W` range from 10 to 60 in 10 foot increments

**`Assesment Task :`** Code a capacity estimator using a nested set of `for` loops and the print command. You might want to try using `f-strings` to format a decent looking table.

In [1]:
import numpy as np
S = np.linspace(3,7,9)
W = np.linspace(10,60,6)
S,W


(array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]),
 array([10., 20., 30., 40., 50., 60.]))

In [2]:
S1 = np.arange(3,7,0.5);
W1 = np.arange(10,60,10)
S1,W1

(array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5]), array([10, 20, 30, 40, 50]))

In [3]:
for x in S:
    for y in W:
        print(x, ' ', y, ' what is the field capacity')

3.0   10.0  what is the field capacity
3.0   20.0  what is the field capacity
3.0   30.0  what is the field capacity
3.0   40.0  what is the field capacity
3.0   50.0  what is the field capacity
3.0   60.0  what is the field capacity
3.5   10.0  what is the field capacity
3.5   20.0  what is the field capacity
3.5   30.0  what is the field capacity
3.5   40.0  what is the field capacity
3.5   50.0  what is the field capacity
3.5   60.0  what is the field capacity
4.0   10.0  what is the field capacity
4.0   20.0  what is the field capacity
4.0   30.0  what is the field capacity
4.0   40.0  what is the field capacity
4.0   50.0  what is the field capacity
4.0   60.0  what is the field capacity
4.5   10.0  what is the field capacity
4.5   20.0  what is the field capacity
4.5   30.0  what is the field capacity
4.5   40.0  what is the field capacity
4.5   50.0  what is the field capacity
4.5   60.0  what is the field capacity
5.0   10.0  what is the field capacity
5.0   20.0  what is the f